/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as StudiosRouteImport } from './routes/studios'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldsVihaliRouteImport } from './routes/worlds/vihali'
import { Route as WorldsKochuniRouteImport } from './routes/worlds/kochuni'
import { Route as WorldsChakraRouteImport } from './routes/worlds/chakra'
import { Route as ProductsLunaRouteImport } from './routes/products/luna'
import { Route as ProductsForgeRouteImport } from './routes/products/forge'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiosRoute = StudiosRouteImport.update({
  id: '/studios',
  path: '/studios',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsVihaliRoute = WorldsVihaliRouteImport.update({
  id: '/worlds/vihali',
  path: '/worlds/vihali',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsKochuniRoute = WorldsKochuniRouteImport.update({
  id: '/worlds/kochuni',
  path: '/worlds/kochuni',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsChakraRoute = WorldsChakraRouteImport.update({
  id: '/worlds/chakra',
  path: '/worlds/chakra',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsLunaRoute = ProductsLunaRouteImport.update({
  id: '/products/luna',
  path: '/products/luna',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsForgeRoute = ProductsForgeRouteImport.update({
  id: '/products/forge',
  path: '/products/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/studios': typeof StudiosRoute
  '/vision': typeof VisionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/products/forge': typeof ProductsForgeRoute
  '/products/luna': typeof ProductsLunaRoute
  '/worlds/chakra': typeof WorldsChakraRoute
  '/worlds/kochuni': typeof WorldsKochuniRoute
  '/worlds/vihali': typeof WorldsVihaliRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/studios': typeof StudiosRoute
  '/vision': typeof VisionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/products/forge': typeof ProductsForgeRoute
  '/products/luna': typeof ProductsLunaRoute
  '/worlds/chakra': typeof WorldsChakraRoute
  '/worlds/kochuni': typeof WorldsKochuniRoute
  '/worlds/vihali': typeof WorldsVihaliRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/studios': typeof StudiosRoute
  '/vision': typeof VisionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/products/forge': typeof ProductsForgeRoute
  '/products/luna': typeof ProductsLunaRoute
  '/worlds/chakra': typeof WorldsChakraRoute
  '/worlds/kochuni': typeof WorldsKochuniRoute
  '/worlds/vihali': typeof WorldsVihaliRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/studios'
    | '/vision'
    | '/legal/privacy'
    | '/legal/terms'
    | '/products/forge'
    | '/products/luna'
    | '/worlds/chakra'
    | '/worlds/kochuni'
    | '/worlds/vihali'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/studio'
    | '/studios'
    | '/vision'
    | '/legal/privacy'
    | '/legal/terms'
    | '/products/forge'
    | '/products/luna'
    | '/worlds/chakra'
    | '/worlds/kochuni'
    | '/worlds/vihali'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/studios'
    | '/vision'
    | '/legal/privacy'
    | '/legal/terms'
    | '/products/forge'
    | '/products/luna'
    | '/worlds/chakra'
    | '/worlds/kochuni'
    | '/worlds/vihali'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRoute
  StudiosRoute: typeof StudiosRoute
  VisionRoute: typeof VisionRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ProductsForgeRoute: typeof ProductsForgeRoute
  ProductsLunaRoute: typeof ProductsLunaRoute
  WorldsChakraRoute: typeof WorldsChakraRoute
  WorldsKochuniRoute: typeof WorldsKochuniRoute
  WorldsVihaliRoute: typeof WorldsVihaliRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studios': {
      id: '/studios'
      path: '/studios'
      fullPath: '/studios'
      preLoaderRoute: typeof StudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/vihali': {
      id: '/worlds/vihali'
      path: '/worlds/vihali'
      fullPath: '/worlds/vihali'
      preLoaderRoute: typeof WorldsVihaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/kochuni': {
      id: '/worlds/kochuni'
      path: '/worlds/kochuni'
      fullPath: '/worlds/kochuni'
      preLoaderRoute: typeof WorldsKochuniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/chakra': {
      id: '/worlds/chakra'
      path: '/worlds/chakra'
      fullPath: '/worlds/chakra'
      preLoaderRoute: typeof WorldsChakraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/luna': {
      id: '/products/luna'
      path: '/products/luna'
      fullPath: '/products/luna'
      preLoaderRoute: typeof ProductsLunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/forge': {
      id: '/products/forge'
      path: '/products/forge'
      fullPath: '/products/forge'
      preLoaderRoute: typeof ProductsForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRoute,
  StudiosRoute: StudiosRoute,
  VisionRoute: VisionRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ProductsForgeRoute: ProductsForgeRoute,
  ProductsLunaRoute: ProductsLunaRoute,
  WorldsChakraRoute: WorldsChakraRoute,
  WorldsKochuniRoute: WorldsKochuniRoute,
  WorldsVihaliRoute: WorldsVihaliRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
