/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as VisionRouteImport } from "./routes/vision";
import { Route as StudiosRouteImport } from "./routes/studios";
import { Route as StudioRouteImport } from "./routes/studio";

import { Route as IndexRouteImport } from "./routes/index";
import { Route as WorldsVihaliRouteImport } from "./routes/worlds/vihali";
import { Route as WorldsKochuniRouteImport } from "./routes/worlds/kochuni";
import { Route as WorldsChakraRouteImport } from "./routes/worlds/chakra";
import { Route as LegalTermsRouteImport } from "./routes/legal/terms";
import { Route as LegalPrivacyRouteImport } from "./routes/legal/privacy";
import { Route as ProductsLunaRouteImport } from "./routes/products/luna";
import { Route as ProductsForgeRouteImport } from "./routes/products/forge";

const VisionRoute = VisionRouteImport.update({
  id: "/vision",
  path: "/vision",
  getParentRoute: () => rootRouteImport,
});

const StudiosRoute = StudiosRouteImport.update({
  id: "/studios",
  path: "/studios",
  getParentRoute: () => rootRouteImport,
});

const StudioRoute = StudioRouteImport.update({
  id: "/studio",
  path: "/studio",
  getParentRoute: () => rootRouteImport,
});

const ProductsLunaRoute = ProductsLunaRouteImport.update({
  id: "/products/luna",
  path: "/products/luna",
  getParentRoute: () => rootRouteImport,
});

const ProductsForgeRoute = ProductsForgeRouteImport.update({
  id: "/products/forge",
  path: "/products/forge",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});

const WorldsVihaliRoute = WorldsVihaliRouteImport.update({
  id: "/worlds/vihali",
  path: "/worlds/vihali",
  getParentRoute: () => rootRouteImport,
});

const WorldsKochuniRoute = WorldsKochuniRouteImport.update({
  id: "/worlds/kochuni",
  path: "/worlds/kochuni",
  getParentRoute: () => rootRouteImport,
});

const WorldsChakraRoute = WorldsChakraRouteImport.update({
  id: "/worlds/chakra",
  path: "/worlds/chakra",
  getParentRoute: () => rootRouteImport,
});

const LegalTermsRoute = LegalTermsRouteImport.update({
  id: "/legal/terms",
  path: "/legal/terms",
  getParentRoute: () => rootRouteImport,
});

const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: "/legal/privacy",
  path: "/legal/privacy",
  getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
  IndexRoute: IndexRoute,

  ProductsLunaRoute: ProductsLunaRoute,
  ProductsForgeRoute: ProductsForgeRoute,
  StudioRoute: StudioRoute,
  StudiosRoute: StudiosRoute,
  VisionRoute: VisionRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  WorldsChakraRoute: WorldsChakraRoute,
  WorldsKochuniRoute: WorldsKochuniRoute,
  WorldsVihaliRoute: WorldsVihaliRoute,
};

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes();
